### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by pkmnmstr98** [Instinkt-Servers/PS2QuestSystem#1]
[ps2_quests] addons/ps2_quests/lua/quest/cl_main.lua:42: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. func - addons/ps2_quests/lua/quest/cl_main.lua:42
    3. unknown - lua/includes/extensions/net.lua:33

Addon seems to be missing some code. There's no Pointshop2.InventoryPanels2 variable anywhere :(. Seems to be a custom modification of pointshop2.

**Comment by Instinkt-Servers** [comment]
Can you please do the following and give me feedback?

Go to: pointshop2\lua\ps2\client\tabs\inventory_tab
Open: cl_0_dpointshopinventorytab.lua

Replace it with:
https://pastebin.com/bGyhB4Xt

**Comment by pkmnmstr98** [comment]
Looks good! Seems to have fixed the issue. You wouldn't happen to have colored inventory panels that show rank/grade of the item :)?

**Comment by Instinkt-Servers** [comment]
tbh i am not longer active in GarrysMod. You can hover with the Mouse over the icons to see the reward.
When i am absolutly bored i can add an option like this.
